services:
  - type: web
    name: byopstudio
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r backend/requirements.txt && cd frontend && yarn install --frozen-lockfile && yarn build"
    startCommand: "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: byopstudio
      - key: CORS_ORIGINS
        sync: false
